### ISSUE TITLE
Deploy as ActiveX / OCX

### ISSUE THREAD

**Issue by PWSys** [MicrosoftEdge/WebView2Browser#14]
Will this be availble wrapped in an ActiveX or OCX object?  This would be helpful for use with exsiting applications that currently rely on Internet Explorer 11.

**Comment by JonathanRowley** [comment]
What’s your use case @PWSys? WebView2 is meant to be a control you can use to develop apps outside of regular web browsing contexts so I’m not sure this would be helpful as an activeX component for IE if that’s what you are suggesting? Both of those things (IE and ActiveX) are also deemed as legacy products so there likely won’t be any new development from Microsoft.

**Comment by PWSys** [comment]
Hi @JonathanRowley , 
My use case covers both current and legacy applications that support ActiveX controls for use in HMIs in industrial environments.  They allow displaying ActiveX controls within their interface. A common use is to drop in an Internet Explorer ActiveX object to display web content within the HMI.  These are generally running in limited access environments where users can only use the HMI. and opening an instance of Edge is not an option.

Currently Internet Explorer 11 is the most recent mainstream browser that supports being deployed via ActiveX.  It would be nice if WebView2 could be deployed as an ActiveX object to allow consumption of modern web content within these applications and give a path for migration off of Internet Explorer 11.

**Comment by JonathanRowley** [comment]
As this is the repo for the webview2 demo browser this probably isn’t a great place to discuss use cases for the webview2 control, however, if you cannot install third party apps in your environment and are limited to running inside a hosted IE runtime you don’t manage, you could look at other options such as XBAP to host a chromium based web control or use IE to stream content from a remote chromium instance. 

On a side note, webview2 also requires Chromium Edge to be installed on the target device so I’m not sure if that would also be an issue for you? 

Personally, if it’s new JS API’s you’re after, I’d be inclined to write the app with basic HTML forms and process the logic on a backend server and just enhance form submissions to XHR ones in the client.

**Comment by JonathanRowley** [comment]
In addition, a quick google search reveals there are a few third party ActiveX implementations of the chromium (V8 and Blink) engine but these would require installation on the target machine so that may or may not be another option for you.

**Comment by honkinberry** [comment]
I second the need for an insertable OCX control.
The only one we've found is WebKitX, but the way they handle registration as well as installation is completely unacceptable.
We need a drop-in replacement for the IE OCX control.

**Comment by SUngemach** [comment]
I second this too, sincerely! We work with local dynamically generated JS for security reasons (portable software, using web technology w/o relying on code on a server which might be temporarily unavailable), and we frame the Googe Map API which we also want to run completely locally. Our use cases also include rendering various web content in a control and to talk to it via DOM model.

Alll of this worked seamlessly for over a decade with MSIE control as OCX. Now MSIE is completely deprecated, and actual GM JS API refuses to run (to be precise it runs, but with a disturbing, prominent warning) in MSIE, telling the end user to "use a modern browser". But our environment is NOT VIsual Studio.

SO yes, we urgently need something to bring Webview2 on or windows without installation since we write portable software!

**Comment by honkinberry** [comment]
Note, we found this Antview OCX, which works perfectly.
https://antview.dev/

**Comment by victorhuangwq** [comment]
Closed as not relevant to WebView2
