### ISSUE TITLE
Replace Edge on windows with something like this browser

### ISSUE THREAD

**Issue by giovariot** [MicrosoftEdge/WebView2Browser#36]
I noticed that in windows 11 there are currently two almost complete "versions" of edge: one is the browser itself and the other one in edge webview2.

I don't really know if it's even feasible or advisable as I'm not a programmer but it would be awesome to have a "minimal" edge browser version that leverages webview2 components so that disk space usage is optimised. 

Writing this here as it seems to me the nearest thing to what I think should be edge browser on windows.

**Comment by TReKiE** [comment]
The disk space for the various copies of the Edge files has already been optimized by using hard links, it just isn't obvious in File Explorer.  

For example, if you open up a Command Prompt/Windows Terminal, navigate to the current Edge folder (right now it's `C:\Program Files (x86)\Microsoft\Edge\Application\95.0.1020.44`), and execute `fsutil hardlink list msedge.dll`, you'll see the file has three links:

```
C:\Program Files (x86)\Microsoft\Edge\Application\95.0.1020.44>fsutil.exe hardlink list msedge.dll
\Program Files (x86)\Microsoft\EdgeCore\95.0.1020.44\msedge.dll
\Program Files (x86)\Microsoft\EdgeWebView\Application\95.0.1020.44\msedge.dll
\Program Files (x86)\Microsoft\Edge\Application\95.0.1020.44\msedge.dll
```
So the three copies of msedge.dll, at 177 MB each, only take up 177 MB in total because they're hard links to the same file.  

With that in mind, I believe your idea would probably end up using up more space than saving anything.

If you're at all interested in hard links, [this shell extension](https://schinagl.priv.at/nt/hardlinkshellext/hardlinkshellext.html) I've used for many years is quite useful, and you can also [see the links graphically](https://schinagl.priv.at/nt/hardlinkshellext/enumeratehardlinks.png) in Explorer instead of needing to use fsutil.
